### PR TITLE
Implements github actions lint

### PR DESCRIPTION
**Pull request by dionisioedu**

### CODE REVIEW

**Comment by gastsail** [comment]
hey @dionisioedu thanks you so much for your contribution ! Could you please briefly describe what lint options you added to the project and what they do ? thanks

**Comment by dionisioedu** [comment]
> hey @dionisioedu thanks you so much for your contribution ! Could you please briefly describe what lint options you added to the project and what they do ? thanks

It runs some validations on the code at every new pull request.

**Comment by gastsail** [comment]
yep, which validations it runs ? thanks @dionisioedu

**Comment by dionisioedu** [comment]
> yep, which validations it runs ? thanks @dionisioedu

In the page:
Runs a Gradle Lint check on all files in the repo and creates a Github "Check Run" report with the results

https://github.com/mobileposse/github-android-lint-action

**Comment by gastsail** [comment]
Thanks for your contribution @dionisioedu

**Pull request merged**
